import { IservPK } from "../Interfaces/IservPK";

export const ServeryDal: IservPK[] = [
    {
        id: 1,
        nazvanie: 'BIS',
        tip: 'PK',
        raspologenie: 'Кабинет 12',
        orgEd: "шт.",
        inventerNomer: "АИ92",
        teg: 'green',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 2,
        nazvanie: 'BIS_SIS',
        tip: 'Nout',
        raspologenie: 'Кабинет 10',
        orgEd: "шт.",
        inventerNomer: "АИ921",
        teg: 'green',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 3,
        nazvanie: 'AIU',
        tip: 'PK',
        raspologenie: 'Кабинет 1',
        orgEd: "шт.",
        inventerNomer: "АИ90",
        teg: 'green',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 4,
        nazvanie: 'BNS',
        tip: 'PK',
        raspologenie: 'Кабинет 2',
        orgEd: "шт.",
        inventerNomer: "АИ01",
        teg: 'grey',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 5,
        nazvanie: 'SS1',
        tip: 'PK',
        raspologenie: 'Кабинет 2',
        orgEd: "шт.",
        inventerNomer: "АИ9882",
        teg: 'green',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 6,
        nazvanie: 'OUPIK',
        tip: 'Monoblok',
        raspologenie: 'Кабинет 12',
        orgEd: "шт.",
        inventerNomer: "АИ77",
        teg: 'red',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 7,
        nazvanie: 'iPiS',
        tip: 'Monoblok',
        raspologenie: 'Кабинет 2',
        orgEd: "шт.",
        inventerNomer: "KK92",
        teg: 'grey',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 8,
        nazvanie: 'BuS',
        tip: 'PK',
        raspologenie: 'Кабинет 12',
        orgEd: "шт.",
        inventerNomer: "АИ7792",
        teg: 'red',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 9,
        nazvanie: 'Bik_Bum',
        tip: 'Nout',
        raspologenie: 'Кабинет 7',
        orgEd: "шт.",
        inventerNomer: "АИH92",
        teg: 'grey',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 10,
        nazvanie: 'System',
        tip: 'Monoblok',
        raspologenie: 'Подвал',
        orgEd: "шт.",
        inventerNomer: "АИ92",
        teg: 'gold',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 11,
        nazvanie: 'Siska',
        tip: 'PK',
        raspologenie: 'Столовая',
        orgEd: "шт.",
        inventerNomer: "92",
        teg: 'green',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 12,
        nazvanie: 'Robin i Gud',
        tip: 'Monoblok',
        raspologenie: 'Кабинет 22',
        orgEd: "шт.",
        inventerNomer: "АИ9702",
        teg: 'gold',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 14,
        nazvanie: 'Byaka',
        tip: 'PK',
        raspologenie: 'Кабинет 1',
        orgEd: "шт.",
        inventerNomer: "А92",
        teg: 'green',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 15,
        nazvanie: 'Salo',
        tip: 'Nout',
        raspologenie: 'Кабинет 4',
        orgEd: "шт.",
        inventerNomer: "АИ8892",
        teg: 'gold',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 16,
        nazvanie: 'Destyni',
        tip: 'PK',
        raspologenie: 'Кабинет 12',
        orgEd: "шт.",
        inventerNomer: "DDdi12",
        teg: 'green',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 17,
        nazvanie: 'Pikachu',
        tip: 'PK',
        raspologenie: 'Кабинет 22',
        orgEd: "шт.",
        inventerNomer: "АИ9288",
        teg: 'green',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 18,
        nazvanie: 'B12IS',
        tip: 'PK',
        raspologenie: 'Кабинет 10',
        orgEd: "шт.",
        inventerNomer: "АИ9200",
        teg: 'green',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 19,
        nazvanie: 'B0IS',
        tip: 'Nout',
        raspologenie: 'Кабинет 7',
        orgEd: "шт.",
        inventerNomer: "А1И92",
        teg: 'grey',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 20,
        nazvanie: 'ByayaIS',
        tip: 'PK',
        raspologenie: 'Кабинет 6',
        orgEd: "шт.",
        inventerNomer: "077АИ92",
        teg: 'green',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 21,
        nazvanie: 'Hyu',
        tip: 'Nout',
        raspologenie: 'Кабинет 9',
        orgEd: "шт.",
        inventerNomer: "А889И92",
        teg: 'green',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 22,
        nazvanie: 'Berr',
        tip: 'SuperPK',
        raspologenie: 'Туалет',
        orgEd: "шт.",
        inventerNomer: "007",
        teg: 'red',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },
    {
        id: 23,
        nazvanie: 'IS',
        tip: 'PK',
        raspologenie: 'Кабинет 7',
        orgEd: "шт.",
        inventerNomer: "А795И92",
        teg: 'green',
        dataSozdaniya: new Date().toLocaleDateString(),
        dataObnovleniya: new Date().toLocaleDateString(),
        dataAudita: new Date().toLocaleDateString(),
    },

]